### ISSUE TITLE
Unexpected $end in startup file

### ISSUE THREAD

**Issue by pat-s** [HenrikBengtsson/startup#18]
`update-packages.R` content

```
pacman::p_up()
```

> Error: Failure processing startup file ‘/home/patrick/.Rprofile.d/rstudio=FALSE/._update-packages.R’: /home/patrick/.Rprofile.d/rstudio=FALSE/._update-packages.R:1:1: unexpected $end

**Comment by HenrikBengtsson** [comment]
Thanks for reporting this.  Before anything else, I'd like to be able reproduce this error `unexpected $end` and figure out what is actually generating it.  Because of this, could please gzip the problematic file and send it to me:
```sh
gzip /home/patrick/.Rprofile.d/rstudio=FALSE/._update-packages.R
```
That is send the generated `._update-packages.R.gz` file.  I'm really curious what it contains.  Please do that.

Then, could it be that `._update-packages.R` some type of temporary file that your editor creates when working with `update-packages.R`?  Note the `._` prefix.  If so, then I could add a filter against such temporary files, just like startup now excludes files ending with a `~` (generated by Emacs), e.g. `update-packages.R~`.



Next, it is not safe to update R packages during startup, regardless of method (AFAIK).  Attempts to update a package will one way or the other call `utils::update.packages()`, which will in turn launch a new R session in the background.  Now, that new R session will then in turn source the R startup files and boom... you'll have an infinite recursive loop of R session being started.  The startup package already detects and prevent any attempt to calling `update.packages()`.  I've now also [added same same protection against `pacman::p_up()`](https://github.com/HenrikBengtsson/startup/commit/14e48ba6128863b8bfd219e057b16dd89c3f1867) to the next release of the package.

**Comment by pat-s** [comment]
[update-packages.R.zip](https://github.com/HenrikBengtsson/startup/files/741781/update-packages.R.zip)

I do not see a temporary file. I used RStudio to create the file, then saved it in `.Rprofile.d`. Hopefully you can reproduce the error. 

I noticed the inf loop when using the "non-startup" (=default) way (`.Rprofile`) calling `pacman::p_up()`. Thanks for the hint to better avoid this approach.

**Comment by HenrikBengtsson** [comment]
Ah... the infamous clutter added by macOS;
```sh
$ tree -a
.
├── __MACOSX
│   └── ._update-packages.R
└── update-packages.R
```
I'll have next release filter those out as well.

PS. I'm on Linux and I _cannot_ reproduce the `unexpected $end` error, neither on plain R or via RStudio.  It could be an encoding / macOS thing that chokes on that 210-byte binary byte stream that `._update-packages.R` contains.  Anyways, this is clearly a file that should filtered out so nothing really to worry about.

**Comment by HenrikBengtsson** [comment]
Next version will now skip the hidden `__MACOS` directories created by macOS.  You can can install this version already now by:
```r
source('http://callr.org/install#HenrikBengtsson/startup@develop')
```
Also, if one of your startup script files calls `p_up()` you get the following informative error:
```r
Error in check_rprofile_update_packages(all = all, debug = debug) : 
  UNSAFE STARTUP CALL DETECTED (pacman::p_up()): Updating or installing R packages during R startup will recursively spawn off an infinite number of R processes. Please remove offending call in order for .Rprofile scripts to be applied: /home/hb/.Rprofile.d/issue_18/update-packages.R
```

BTW, I did indeed see the `unexpected $end` error if I ran R via `R CMD`, e.g.
```sh
R CMD build startup
Error: Failure processing startup file '/home/hb/.Rprofile.d/issue_18/__MACOSX/._update-packages.R': /home/hb/.Rprofile.d/issue_18/__MACOSX/._update-packages.R:1:1: unexpected $end
```

**Comment by pat-s** [comment]
Hi Henrik,

I just came across this error again. 

I copied a startup file (`load-at-start.R`) created in my macOS Desktop application to my server `.Rprofile.d` folder with the following contents:

`library(pacman)`

and got 

`Error: Failure processing startup file ‘/home/patrick/.Rprofile.d/._load-at-start.R’: /home/patrick/.Rprofile.d/._load-at-start.R:1:1: unexpected $end`

I then remembered this issue, deleted the file again and recreated it in RStudio Server running on Debian Server. After having created and saved the file in the Debian environment, the error message was gone. 

Is there some encoding stuff going on depending on which file System an `.R` file was created?

**Comment by HenrikBengtsson** [comment]
I don't have macOS so I cannot play with this myself, so for  my sake of understanding how this happens, and to best workaround this, exactly how do you copy the files, e.g. do you copy from the command line or using a GUI? Do you copy over a remote login, e.g. SCP, or SFTP? Also, what OS is your server running?

**Comment by HenrikBengtsson** [comment]
Thanks, I think I got what I need.  I've learned a bit more about this "feature" which happens not only when zip'ed (what I though a few months ago), but also when files are copied over to non-macOS file systems (like here).

Some pointers (mostly for myself):
* https://apple.stackexchange.com/questions/14980/why-are-dot-underscore-files-created-and-how-can-i-avoid-them
* http://stackoverflow.com/questions/10323580/what-are-all-these-hidden-prefixed-files-that-are-in-my-git-repo

The plan is to (i) detect such `._` files (and some other macOS-specific files), (ii) make sure they are not files and just happening to have the same filename pattern, and only then (iii) filter them out.

**Comment by HenrikBengtsson** [comment]
Install the develop branch (`source('http://callr.org/install#HenrikBengtsson/startup@develop')`) on that Unix server where you get the errors and see if my fixes there resolve the problem.

**Comment by pat-s** [comment]
works! Copied again the file created in macOS to the unix server and got the same failure again when using v0.6.0 -> update to v0.6.0-9000 and everything works.

**Comment by HenrikBengtsson** [comment]
Good to hear.

**Comment by HenrikBengtsson** [comment]
FYI, startup 0.6.1, fixing this issue, just landed on CRAN; macOS binaries should be available within a few days.
